### ISSUE TITLE
Create factory method for Model class?

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#100]
Right now, we use conditional compilation to create different platform implementations of the abstract Model class. Would it be better, and more consistent with other classes, to have a factory method that creates the concrete subclass object?

**Comment by fumik** [comment]
If we adopt this strategy, we have to create a separate class for each class that has GPU methods. 
For example, we will have SingleThreadedAllSpikingNeurons, GPUAllSpikingNeurons, SingleThreadedAllLIFNeurons, GPUAllLIFNeurons, SingleThreadedAllSpikimgSynapses, GPUAllSpikimgSynapses, SingleThreadedConnGrowth, GPUConnGrowth...etc. Also if we keep multithreaded model, we will need other classes for multithreaded model. This will make the system more complicated.

**Comment by stiber** [comment]
The idea is just for uniformity of creation in BGDriver.cpp. There would still be a need for conditional compilation, just not in main(). Anyway, something to think about.

**Comment by fumik** [comment]
Another option is that we have a single Model class. Inside the model class, we use #ifdef to separate between single ahead and GPU code. This is the way other classes use. DO you like this way?
