### ISSUE TITLE
Rename saveMemory() to serialize() and loadMemory() to deserialize()

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#102]
These methods are in multiple classes, certainly including Model. While they may no longer work, their intent is to completely save the state of the simulation to an ostream (serialize it) so that it can be resumed later (deserialized). This is useful in at least two scenarios:

1. Running a simulation to set up a network, with the idea of using that as a starting point for multiple continuations with different parameters.
2. Running a simulation on a shared machine like hyak, where you need to checkpoint the simulation regularly because it is subject to being killed at any time. Simulation could then be restarted from last checkpoint.

Note that this is independent of these methods actually working completely; that's another issue. Anyway, the names are confusing so I'm labeling this a bug.

**Comment by fumik** [comment]
Fixed
