### ISSUE TITLE
Should Recorder objects be created like ISInput objects?

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#104]
Right now, Connections objects create Recorder objects. Why aren't Recorder objects and ISInput objects created analogously, using patterns and methods of similar form?

**Comment by fumik** [comment]
Because Recorder classes depends on Connections classes, Connections classes create them.
For example, some of growth related properties will be recorded by the Hdf5/XmlGrowthRecorder classes, which are created by the ConnGrowth class.
