### ISSUE TITLE
Change factory class to use conditional compilation to switch class types

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#109]
Modify FClassOfCategory.cpp so that it has conditional compilation statements, and Makefile so that the switch is there. The idea is, as a stopgap, to not have the hard coding for different models buried inside this class's methods.

**Comment by fumik** [comment]
Each createXXXXX() method in the FClassOfCategory class get the parameter (TiXmlElement* parts), which is the pointer to the xml parameter description. The idea is that once we define the format how to specify class name in the description file, we can get the name of the class of each category and create the instance of the specified class.

**Comment by stiber** [comment]
Right, all I've done is modify the code for now so that this can be done in the Makefile, rather than having it hardcoded in that class. This will make it a little more obvious in the interim; my guess is it will be a little while before we revise our parameter file format and incorporate that into the program (and the workbench). I've committed the change to a separate branch, and will hold off on merging it into the main branch until our 3/3 meeting.
