### ISSUE TITLE
Clean up in aisle updateSynapsesWeightsDevice()

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#139]
Line 111 looks like:

```
synapseType type = synType(neuron_type_map_d, src_neuron, dest_neuron);
```

This is only used on lines 133, 134:

```
allSynapsesDevice->W[iSyn] = W_d[src_neuron * num_neurons
      + dest_neuron] * synSign(type) * AllSynapses::SYNAPSE_STRENGTH_ADJUSTMENT;
```

It would be clearer to just look up the source neuron type (neuron_type_map_d[src_neuron]) and use this to set the synapse sign. Every outgoing synapse from the current neuron has the same sign. This only needs to be computed once per thread.

**Comment by stiber** [comment]
Actually, given that this kernel needs to be updated so that each thread executes for a destination neuron, you'll need to look up the source neuron type for _each_ synapse. So, the code can be something like:
```
synSign(synType(neuron_type_map_d, src_neuron, dest_neuron))
```

**Comment by stiber** [comment]
Also, it seems you don't need synapse_adjusted in the innermost loop.

**Comment by stiber** [comment]
Re-reading this, in the context of cleaning up issues for summer 2016, I'm not sure if this applies to the main branch or forward-refactor.

**Comment by fumik** [comment]
After refactoring, each kernel thread is invoked by a destination neuron basis, so we need to look up source neuron type for each synapse. 

We use the global neuron number for source and destination neurons.
