### ISSUE TITLE
Fix the size_t issue

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#142]
It appears that the type size_t is problematic on the GPU (at least, on cerberus, so Fermi architecture). In tests on cerberus, incrementing or adding to a size_t caused either nothing to happen or weird errors. On the other hand, uint32_t was fine. There's no reason I can see not to use a uint32_t, unless we really want a type that isn't bound to a set number of bits.

**Comment by stiber** [comment]
FYI, here's an informative, short article on size_t: [Why size_t matters](http://www.embedded.com/electronics-blogs/programming-pointers/4026076/Why-size-t-matters).

**Comment by fumik** [comment]
Added a type BGSIZE in BGTypes.h, and defined it as uint32_t. All variables for array index are now
defined this type.
