### ISSUE TITLE
Decide general method for implementing indirect device function calls

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#151]
Device functions that cannot be identified at linking time. Currently this is done by using function pointers. Problem is when one needs to call a device function that lives in another CUDA module -- for example, when a neuron kernel needs to call a synapse device function. Pointers are only valid when in the same module (compilation unit) as the called function.

Possible approaches:
1. Use something like an enum, rather than a pointer, with a switch to select device function to call. Would require adding code in multiple places to add addition device functions.
2. Implement a dispatch function that holds the pointer. Dispatch function lives in same module as called functions. So, for example, when a neuron kernel/function wants to call preSpikeHit(), it would call a "master" preSpikeHit(), compiled in the Synapse module. That function, in turn, would hold a pointer to the actual synapse type's preSpikeHit().

Other ideas? See #137 for more detail.

**Comment by fumik** [comment]
All global and device functions related to advanceSynapses and
createSynapses are moved into AllSynapsesDeviceFuncs_d.cu file.
All global and device functions related to advanceNeurons are moved
into AllNeuronsDeviceFuncs_d.cu file.
So there are no inter modules calls between global and device
functions.
Also eliminated function pointers, and instead using switch statement
to call appropriate device functions.

commit 048486ac197b16bcca1a8b034034ba1667090001
