### ISSUE TITLE
HDF5 recorders should save deltaT

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#164]
Since spike times are saved as step number, rather than time in seconds or ms, deltaT needs to be saved. The alternative would be to save using seconds or ms.

**Comment by fumik** [comment]
deltaT is written in HDFF5 files as the tag name 'attrPNUint'. (The name might be typo. This will be 'attrPNUnit')

**Comment by stiber** [comment]
Is the tag name in HDF5 the variable name? Any reason for that name, and not "deltaT" or similar?

**Comment by fumik** [comment]
Assuming all data set will have their own unit and deltaT is a kind of simulation internal data, so it must be independent from the representation of data set in hdf5 file. Therefore I added attrPNUint data for Probed Neurons Data Unit to interpret the data.

**Comment by stiber** [comment]
Actually, however, deltaT isn't purely internal information. It is at times necessary to know deltaT in order to interpret the data (such as in this case). The alternative would be to save spike times as times, rather than step numbers.

**Comment by stiber** [comment]
It seems that this is OK, modulo any typos. I'll put a "review HDF5 file format/organization" in Kerika, for this coming summer.
