### ISSUE TITLE
Izhikevich model results seem to depend on poolsize dimensionality

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#165]
Since the IZH model connectivity is complete, results should only depend on the number of neurons, not their physical layout (poolsize x and y). In fact, this isn't the case, at least when x=1 and y=1000.

**Comment by fumik** [comment]
Try to change threshConnsRadius="50" to a bigger value, such as "1000" when x=1 and y=1000.

**Comment by stiber** [comment]
Yes, @JewelYLee noticed this. So, perhaps this is resolved? @JewelYLee, I know that there is some stuff that you're working on that is "hacking around" and not meant to push to the repo, but see if there's a need to update any of the configuration files there and push that.

**Comment by JewelYLee** [comment]
Thanks @fumik! @stiber Yes, for this issue, there is nothing to update in configuration files. I'll add a comment to note that if users change the pool size they should change the connection radius accordingly. I'll close this issue then!
