### ISSUE TITLE
Need to update all existing config (and validation?) parameter files for new format

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#170]
Probably the fastest thing to do would be to hand edit these or re-generate them with Workbench. In that case, it would make sense to not try to re-create the NList files, but just make blank or very simple ones and replace them with the old NList files, slightly edited to start with <?xml...> declaration.

**Comment by stiber** [comment]
Izhikevich is done; others not.

**Comment by stiber** [comment]
I believe that I have changed all of the config files and NList files. @fumik , could you spot check this on the issue-170 branch, since you've been blocked on your task? One unanswered question (for me): what is the difference between NList/activeNList_0.10_10000.xml and Nlist/activeNList_0.10_10000_2.xml? I don't know that I've used the correct one; they were not consistently used in the existing config files.

**Comment by stiber** [comment]
Need to consider whether to just delete the "validation" directory, since we're not using it anymore.

**Comment by fumik** [comment]
Nlist/activeNList_0.10_10000_2.xml is used when the fraction of excitatory neurons is 0.80. Because all spontaneously active neurons should not be inhibitory neurons, we adjust the positions of active neurons of activeNList_0.10_10000.xml and make a new neurons list activeNList_0.10_10000_2.xml.

**Comment by fumik** [comment]
I need configuration files in validation directory to test/validate the new code.

**Comment by fumik** [comment]
Looks like static_izh_1000.xml is not modified yet.

**Comment by stiber** [comment]
Need to delete probed neuron list file from all tR* configfiles that don't have a file specified.

**Comment by stiber** [comment]
Also need to fix config files in validation directory.

**Comment by stiber** [comment]
And more input from Tom:

> I just kept thinking about the problem we hit on yesterday's meeting. I figured out the problem is the Tag name in your XML file for probed neuron is not correct. The tag in your XML file is "prbNListFileName". The original name of the Tag should be "probedNListFileName". This is my mistake when changing the parameter parsing code. I noticed this and changed it back to "probedNListFileName" later. Maybe I forgot to change the example config files so that you mis-copied them to the new config files.
> 
> In short, the tag name "prbNListFileName" should be changed to "probedNListFileName" to solve the problem. Deleting the tag is not the best solution since the Workbench would still produce the "probedNListFileName" tag in the config file if user didn't enter a value in the "probedNListFileName" parameter.
> 
> FYI, the following is the commit I made to handle the blank value in the NList FileName parameter.
> https://github.com/UWB-Biocomputing/BrainGrid/commit/cf751dfc9bc1ef65b9e21d0ed759ea9fbc1e896d

**Comment by kate-codes** [comment]
We have an issue that I'm not sure where to look in BrainGrid to fix. 

+ make growth
make: `growth' is up to date.
+ ./growth -t validation/test-tiny.xml
reading parameters from xml file
creating instances of all classes
Looking at ModelParams
Looking at NeuronsParams
Looking at SynapsesParams
Looking at ConnectionsParams
Looking at LayoutParams
Attempting to parse a layout param
Attempting to parse a layout param
**Failed loading positions of endogenously active neurons list file NList/ActiveNList2x2.xml:
	Failed to open file**
 error: 0, 0
We end up throwing a layout error anyway
ERROR :: Failed to parse parameter "FClassOfCategory". Cause: Unrecognized layout parameter 'activeNListFileName' was detected.
! ERROR: failed while parsing simulation parameters.
Build step 'Execute shell' marked build as failure

**Comment by stiber** [comment]
My guess is that the NList isn't directly under the directory you're running BrainGrid from. The paths in the parameter file are relative to the pwd where BG is run (unless, of course, they're entered as complete paths). Actually, this is an annoyance of the current setup that probably should be fixed; I'll create an item for it.

**Comment by stiber** [comment]
Created issue #206
