### ISSUE TITLE
Need makefile to build workbench from command line

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#175]

**Comment by stiber** [comment]
This is being accomplished by Maven, @tchoi1131 , right?

**Comment by tchoi1131** [comment]
Yes.
Maven can compile and build the project using the file "pom.xml" created under "Tools/Workbench/WorkbenchProject/". "pom.xml" is used to provide Maven necessary information to compile and build the project.

**Comment by stiber** [comment]
Closed by commit eff23e93940ff370ef75545d9ab665279188f7fe
