### ISSUE TITLE
Performance analysis of multi-cluster simulator (CPU version)

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#176]
1. Run simulations of 100 neurons, 100s * 20 epochs, and 10,000 neurons, 10s * 2 epochs on CPU vision of growth of Master branch and CPU version of growth of Multi-Clusters-Sim branch changing number of clusters. Then record elapsed time of each execution. 

**100 neurons, 100s * 20 epochs**
```
Master - 3735s
1 cluster - 3965s (3965/3735=1.06)
2 clusters - 6381s (6381/3735=1.70)
4 clusters - 5835s (5835/3735=1.56)
8 clusters - 4940s (4940/3735=1.32)
```

**10,000 neurons, 10s * 2 epochs**
```
 Master - 2697s
 1 cluster - 2703s (2703/2697=1.00)
 2 clusters - 4716s (4716/2697=1.75)
 4 clusters - 4410s (4410/2697=1.64)
 8 clusters - 5334s (5334/2697=1.98)
 15 clusters - 4121s (4121/2697=1.53)
```
Execution growth of Multi-Clusters-Sim branch with 1 cluster has almost equal performance of that of Mater branch. However increasing number of clusters does not boost performance. Actually performance drops, and there is no explicit correlation between performance loss and number of clusters. 

2. Next, using API to bind threads to specific CPU cores to avoid thread migration.
```
// Set CPU affinity
pthread_t thread_native = thAdvance.native_handle();

cpu_set_t cpuset;
CPU_ZERO(&cpuset);
CPU_SET(clr_info->clusterID + 1, &cpuset);

pthread_setaffinity_np(thread_native, sizeof(cpu_set_t), &cpuset);
```
Result is:

100 neurons, 100s * 20 epochs, 8 clusters - 8203s 

So performance drops more. 

3. Then use taskset command to set CPU affinity.

**10,000 neurons, 10s * 2 epochs, 2 clusters**
```
default - 4716s
affinity 3-5 - 2862s
```

**10,000 neurons, 10s * 2 epochs, 4 clusters**
```
default - 4410s
affinity 3-7 - 4987s
affinity 3-9 - 3183s
affinity 3-13 - 3193s 
```

Setting CPU affinity slightly affect performance.

4. Used pthread (pthread API is more primitive) barrier synchronization.

**100 neurons, 100s * 20 epochs, 4 clusters - 6457s**

So this does not improve performance. 

Next we set CPU affinity (taskset command) so that it crosses the psychical CPU boundary (0-11, 12 -23) and observe it affects performance. (2 clusters, ‘./growth –t validation/test-large-connected.xml’, 10s * 2 epochs)
```
Affinity: 9, 2720s
Affinity: 9-11, 2796s
Affinity: 10-12, 2807s
Affinity: 11-13, 2767s
```

However no significant difference was found.

Conclusion: utilizing multi-threads will improve performance (ideally increasing number of thread will improve performance linearly). However our results defy expectation. We suppose:

Thread migration - Thread migration will cause memory cache to flush. We tried to use API to bind threads to specific CPU cores to avoid thread migration, and see performance influence. But performance rather dropped. It seems that setting a specific core to a thread would take away opportunity of assigning available CPU core to the thread, and therefore dropped performance. Setting CPU affinity by LINUX command somewhat affected performance, but no clear relationship was found. 
Threads might be hitting each other's cache lines, forcing reloads.
Barrier synchronization - There are three barrier synchronization for every simulation time step. This will cause huge overhead, and this seems to be the main source of performance decline. We modified the barrier synchronization to use more primitive version of API (pthread version), however it did not affect the performance. 
So optimizing performance, we need to consider the way to decrease the number of barrier synchronization. 

Modified code to reduce the number of barrier, but no performance impact.

Move to GPU version of multi-clusters-sim and consider performance issue later.

**Comment by fumik** [comment]
Execution time of the latest host version simulator is slightly slower.

**100 neurons, 100s * 20 epochs**
```
Master - 3735s
1 cluster - 3965s (3965/3735=1.06)
2 clusters - 6381s (6381/3735=1.70)
4 clusters - 5835s (5835/3735=1.56)
8 clusters - 4940s (4940/3735=1.32)
```
