### ISSUE TITLE
Documentation notes for Workbench — to integrate into pages

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#179]
Some of this will eventually need to appear in the wiki; we'll have to separate out what is relevant generally and write it from the point of view of a BG+WB programmer/user.

*The Task*

This task will make more sense when you look at the commit keys on github. The details on this task have changed to include a commit key. This is more specifically asking if the version of the workbench during this specific revision functions as-is. 

*Clone The Repository Rather than Downloading the ZIP on Github...*

You probably need to clone the repository to a directory and use that as an existing source during a new java project with existing sources setup. I think what you did was just downloaded the zip from github. That just gives you the most current version of whichever branch you are looking at. What you want to do is clone the repository to an empty folder using git bash. You can use the following command to clone it: git clone GitHub - UWB-Biocomputing/BrainGrid: A project to facilitate construction of high-performance neural simulations. BrainGrid. First you will have to make the BrainGrid directory and make sure it is empty. So, the state of the code that he wants you to test is here:
(1) Added simulation configuration test model. (2) Changed look and f… · UWB-Biocomputing/BrainGrid@0eda76e · GitHub

*Use Git on the Commandline to Checkout the Specified Revision*

You can use git bash again to change the revision to that commit by using the following command after navigating to the repository directory that you just cloned into: git checkout 0eda76e9ea75fd4608105309899ef1f3291f42ec

*Make a New Project Using the Workbench Source Code You Just Cloned (Rather Than The Zipped Stuff from Github)*

Now, in netbeans, make a new java project with existing sources but dont click finish. click next and it will ask you to add directories containing source code and test code. click add next to the source code and navigate to your repository and then into this directory BrainGrid/Tools/Workbench/ and then select the src folder. Then finish the new project dialog. If you expand the src folder you should see a workbench package (not one of its subpackages), expand that. Then, right click Workbench.java and select run. This will fail to run because it will throw an exception about missing dependencies (ClassNotFoundException). Download the lib folder from the BrainGrid google drive folder I shared with you. Extract those jar files somewhere. Now back in netbeans in the workbench project, right click libraries and select add jar/folder. Now select all those libraries and check the radio button that says relative path in the upper right corner. Then click the add button. That should have fixed it. Now run Workbench.java again.

*Test the Workbench*

Okay, so now that you have all that stuff installed, you can test what Mike wants you to test. What he wants to know is if the user can use the workbench in its state at the point in time where that particular commit was made. From what I remember, the second button in the workflow to build the script is what makes this tricky. When the default options for building the build/execution script come up, they don't specify an SHA1 hash key, but you can put one in. What happens if you don't put one in, is that the repository is cloned and the revision is set to the latest revision of the default branch. That used to work, but since the config file format doesn't match up with what the simulator expects, now you will have to make the build/execution script build the old version of the simulator. Namely, you will have to specify 0eda76e9ea75fd4608105309899ef1f3291f42ec in the box that says SHA1 in the script configuration dialog (2nd button on the workbench). You will also need to set the build option to build and the source code updating to pull. This should make it so that, when you "run" the script that it does the following:

*ScriptSteps*
1. Transfers the configuration file you build
2. Transfers the Neuron Lists that were specified in the config file
3. Transfers the build/exec script for the simulation
4. Attempts to make an empty directory called "Whatever was in the 'Folder' box in the script specification dialog"
5. Attempts to clone from the network location of the remote repository (probably github.com/UWB-Biocomputing/BrainGrid/blahblahblah) to the empty directory from step 4
6. Attempts to checkout the revision specified in SHA1 field of the script configuration dialog that popped up in the 2nd workflow step in the workbench
7. Attempts to "make -clean" to remove any existing binary files from the repository directory
8. Attempts to "make binaryname" to build the simulator
9. Attempts to execute "binaryname" (probably growth) with the configuration file as its input parameter

Now, if the simulator code that was in the repository during the revision: 0eda76e9ea75fd4608105309899ef1f3291f42ec is working correctly (correct make file, no bugs, etc.) and the configuration format matched the format in the workbench, then this task is complete. You will be able to tell if this was successful by looking at the output file that all the printf statements in the script went to. It should be called ProjectName_scriptOutput_vVersionNumber.txt. Download that and open it. After every step that was executed is an exit status. Exit statuses of 0 are successes and any other number is a failure. You should get at least one failure when it clones and pulls because for the clone to succeed, the directory must be empty, and for the pull to succeed, the repository cannot have been up to date. What you are looking for is the execution line near the bottom. It will be something like ./growth MyConfigFile.XML. If it failed, we want to know whether it was because of the config file or the make file (used to build the binaries off of the source code). If it failed, scroll up to where it says make growth, right after make -clean. If that failed then there was a bug during that particular revision... probably the old HDF5 bug, not the new one, there used to be a problem with the make file if I recall.

**Comment by tchoi1131** [comment]
First Draft of the document. Will update and integrate into pages.
[WorkbenchUserManual_v0.1.docx](https://github.com/UWB-Biocomputing/BrainGrid/files/1206837/WorkbenchUserManual_v0.1.docx)
