### ISSUE TITLE
Hdf5Recorder::saveSimData() doesn't write xloc or yloc correctly

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#203]
So, pointers to xloc and yloc are passed to an HDF5 dataset object's write() method. However, this method expects a pointer to a block of memory holding (in this case) native ints -- which is *not* what it's getting, because xloc and yloc are actually VectorMatrix*.

So, how to overcome this? One approach would be to dynamically allocate an int buffer, extract the xloc and yloc data from the VectorMatrix objects, pass the buffer to write(), and deallocate the buffer when done. Seems like this is the "best" approach, and it appears to be what is being done for starterNeurons. @fumik is this correct?

**Comment by fumik** [comment]
Doing it at Hdf5Recorder::saveSimData() is the safest way to solve the issue.

Fixed
