### ISSUE TITLE
Need to refactor AllSynapsesDeviceFuncs_d.cu

### ISSUE THREAD

**Issue by JewelYLee** [UWB-Biocomputing/BrainGrid#205]
Issues #173 and #195 are connected to this. It appears there are common device-side functions that are shared among different synapse classes; these functions have assumptions that aren't always valid. Need to look at the requirements for dynamic spiking synapses and for Izhikevich synapses and come up with a more general solution, or refactor this code so they each have their own functions.

**Comment by stiber** [comment]
Merging this into issue #183
