### ISSUE TITLE
Create checkpoint release for Chaos paper

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#213]
This should be the exact commit that is being used for the simulations. We can then link to it in zenodo to get a permanent DOI.

**Comment by stiber** [comment]
We will need to know the commit that corresponds to the simulator binary that was run to generate our results.

**Comment by JewelYLee** [comment]
commit 4c4699c18cc5e13270dae39ff3708b53c2f610da is the one that I used to run simulations. Simulation configuration files are added under configfiles/ as well

**Comment by stiber** [comment]
Done. Release [1.0-beta](https://github.com/UWB-Biocomputing/BrainGrid/tree/v1.0-beta).

**Comment by stiber** [comment]
Once @stiber can compile BrainGrid and @peterstanton has verified that the config files are good, we will merge the config-file-cleanup branch with the master branch and generate a release.
