### ISSUE TITLE
Refactor core scheduling algorithm to flag

### ISSUE THREAD

**Issue by peterstanton** [UWB-Biocomputing/BrainGrid#228]
## *What kind* of issue is this?
* [ ] Bug report
* [x] Feature request
* [ ] Question not answered in documentation
* [ ] Cleanup needed

## *What* is affected by this?

Performance

## *How* do we replicate the issue/how would it work?

 Currently, peter-multi-thread-sim manually distributes threads of execution to core. Refactor to scale based on hardware_concurrency() calls to get the number of calls, and activate when I use a command line flag. Then I can pull to the main multi-thread-sim branch.

## Expected behavior (i.e. solution or outline of what it would look like)

BrainGrid should use regular hyperthreading unless I set the flag at the commandline.

**Comment by stiber** [comment]
Superseded by multi-cluster sim.
