### ISSUE TITLE
Create conditional compilation setup for validation vs. production version

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#239]
## *What kind* of issue is this?
* [ ] Bug report
* [ ] Feature request
* [ ] Question not answered in documentation
* [X] Cleanup needed

Right now, as described in issue #238, there is a separate branch, multi-clusters-sim-validation, which generates random numbers so that multi-GPU simulations can be directly compared to single-GPU ones. When merging that branch in, let's incorporate a conditional compilation setup so that the validation version can be selected at compile time. This way, we can selectively include code to facilitate validation, even at a performance cost, that can be removed for maximum performance.

## *What* is affected by this?

Simulator

**Comment by fumik** [comment]
Added conditional compilation flag.  "make CVALIDATION='yes' " will make validation version, otherwise make production version.
