### ISSUE TITLE
Minor clean-ups in dotGenerator.py

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#261]
## *What kind* of issue is this?
* [X] Bug report
* [X] Feature request
* [ ] Question not answered in documentation
* [ ] Cleanup needed

1. Script misses inheritance (GPUSpikingCluster from Cluster) in some cases.
2. Help message could be formatted better
3. Clarify that initial "./" is needed.

**Comment by shastrihm** [comment]
So I think the issue was with the fact that in some cases, a classA inherited from classB even when classA.h did not directly include classB.h. I think I have a fix, I'll make a pull request promptly.
