### ISSUE TITLE
Verify that all bug fixes for STDP are propagated to GPU code

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#287]
## *What kind* of issue is this?
* [X] Bug report
* [ ] Feature request
* [ ] Question not answered in documentation
* [ ] Cleanup needed

Besides making notes so that all fixes propagate to the master branch (from the single-threaded simulator), they need to also propagate to the GPU code in the single-threaded simulator.

**Comment by fumik** [comment]
At the master branch, all CUDA_CALLABLE functions are common for both CPU and GPU.

**Comment by stiber** [comment]
Good point. This issue only applies to the single-threaded branch. FYI, @eeemily17 is documenting her changes in the single-threaded branch so that those mods can be brought to the multi-cluster branch.

**Comment by stiber** [comment]
Good point. This issue only applies to the single-threaded branch. FYI, @eeemily17 is documenting her changes in the single-threaded branch so that those mods can be brought to the multi-cluster branch.
