### ISSUE TITLE
Add more detailed documentation for simulation sequence 

### ISSUE THREAD

**Issue by tazzledazzle** [UWB-Biocomputing/BrainGrid#56]
Run through the simulation sequence in detail, add descriptions for the following:
        - parameter checking
        - xml file import
        - Setting up the network
        - Sequence Diagram
        - advanceUntilGrowth
        - advance
        - advanceNeurons --> advanceNeuron
        - advanceSynapses --> advanceSynapse

**Comment by stiber** [comment]
Obsolete.
