### ISSUE TITLE
Error involving single-threaded version makefile and stdint on Mac OSX

### ISSUE THREAD

**Issue by tazzledazzle** [UWB-Biocomputing/BrainGrid#75]
When trying to test the single threaded version of the Brain Grid program, I run into this issue:

$ make growth
g++ -O2 -s -I./common -I./matrix -I./paramcontainer -I./rng -I./tinyxml -I/opt/hdf5/latest/include -Wall -g -pg -c -DTIXML_USE_STL -DDEBUG_OUT  ./common/AllNeurons.cpp -o ./common/AllNeurons.o
In file included from /usr/local/lib/gcc/x86_64-apple-darwin13.1.0/4.9.0/include/stdint.h:9:0,
                 from /usr/include/inttypes.h:225,
                 from ./common/Global.h:51,
                 from ./common/AllNeurons.h:20,
                 from ./common/AllNeurons.cpp:1:
/usr/local/lib/gcc/x86_64-apple-darwin13.1.0/4.9.0/include-fixed/stdint.h:27:32: fatal error: sys/_types/_int8_t.h: No such file or directory
 #include <sys/_types/_int8_t.h>
                                ^
compilation terminated.
make: **\* [common/AllNeurons.o] Error 1

**Comment by stiber** [comment]
I think this is still an outstanding issue. As far as I can tell, modern Macs have either Intel or AMD GPUs, but of course this can change as models are revised. At least, for single threaded compilation, this is a reasonable convenience. And the inability to compile using llvm on a Unix system suggests that there is some scruffiness in the code.

**Comment by stiber** [comment]
Obsolete.
