### ISSUE TITLE
Write up or link to HDF5 documentation in BrainGrid wiki

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#87]
Split off from issue #70.

From Josh Larios:

Hydra is, I think, back up and running. It is experiencing some pretty bad crashes when I try to run it with a graphical console, and I thought I'd solved the problem but then it did it again while I was composing this message, so I guess not. But if I run it with a text console, I believe it should be stable. That'll mean treating it like cssgpu01, though, just something to ssh into. Unfortunately, I think it's the best I can do right now.

It's a CentOS 6.5 installation with the "Software Development Workstation" flavor selected during setup. I've added the stuff for UW NetID authentication (although not UWB authentication this time), the CUDA toolkit and drivers, and HDF5. I may be able to pull some data off the old drives, but I think at least two of them had physically failed, so I'm not sure there's much to recover. I don't remember what else might have been installed before it crashed.

I wrote up the installation of HDF5 at >http://depts.washington.edu/cssuwb/wiki/linux_hdf5_installation for others who might want to do that.

Here are the NetIDs currently allowed to connect to hydra: (,aortez,) (,ethancr,) (,fumik,) (,mcsean,) (,ahoffer,) (,baracs,) (,ctc2,) (,dslab,) (,jdevara,) (,emtosa,) (,rjdamon,) (,hugor,) (,ahoffer,) (,dwise85,) (,pbunn,) (,dlm18,) (,chrisb23,) (,seanb19,)

Plus faculty: (,mfukuda,) (,ksung,) (,stiber,) (,zander,) (,jackels,) (,cfolson,) (,markk,) (,dsocha,) (,hazeline,) (,joemcc,) (,dmclane,) (,peaklist,) (,socha,)

Users with sudo access for administration are you, me and Chris Fox.

Let me know if you'd like any of that changed, or if there's additional software which needs to be installed. There is currently a little under 2TB of disk free, configured as a RAID-5 array for a little bit of redundancy -- if one drive fails, it should be possible to replace it without losing any data.

**Comment by stiber** [comment]
This is probably a sign that we (and others) will be perpetually dealing with HDF5 issues. Probably a good reason to continue to support XML output, as a fallback for when HDF5 issues arise.

**Comment by JewelYLee** [comment]
Write up for getting HDF5 working with BrainGrid, and a potential problem and fixes in wiki page: https://github.com/UWB-Biocomputing/BrainGrid/wiki/Using-BrainGrid-with-HDF5

In the brainGrid website, HDF5 flag setting is explained in section 3. Quickstart (https://github.com/UWB-Biocomputing/BrainGrid/blob/master/docs/3_quickstart.md). Also a link to the wiki page is provided
