### ISSUE TITLE
Look into kernel call blocking

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#95]
I think we've been assuming that kernel calls (on the host side) block, which host side execution not continuing until the kernel finishes. It appears that what might actually be happening is that the next CUDA call is blocking. Anyway, we need to double-check what blocks and what doesn't, and make sure we explicitly call things so they will block. Otherwise, we will eventually run into problem.

**Comment by cburg** [comment]
I don't think that kernel calls are blocking to the host. Take a look at the [cudaDeviceSynchronize()](http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g10e20b05a95f638a4071a655503df25d) call.

**Comment by stiber** [comment]
Thanks, @cburg . I could have sworn kernel calls were blocking, but what probably was the case was that the point was moot, since hardware until recently only supported one kernel execution at a time. Maybe it even was blocking (I really seem to remember one having to do something special to make the call non-blocking). Anyway, it seems to currently be non-blocking; we should make sure that we block until kernel execution finishes before the next kernel invocation or memory transfer.
