### ISSUE TITLE
Fix test-medium.xml

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#98]
The file test-medium.xml (at https://github.com/UWB-Biocomputing/BrainGrid/blob/refactor-stable-cuda/validation/test-medium.xml) has bad indices for its inhibitory neuron list. Replace that list with the valid list from test-medium-2.xml (at https://github.com/UWB-Biocomputing/BrainGrid/blob/refactor-stable-cuda/validation/test-medium-2.xml). Check in the change so it can get folded into the upcoming major merge.

**Comment by harmand7** [comment]
Done changed the test-medium.xml. Left the old indexed neurons in comments for reference
