### ISSUE TITLE
Latest refactor-stable-cuda doesn't compile

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#99]
For some reason, when CUSEHDF5 = no in Makefile, common/Hdf5GrowthRecorder.h gets included, and that file has a (trivial) syntax error on line 31 (extra "). This prevents the program from compiling. However, when CUSEHDF5 = yes, no such error occurs. So:

1. Why is this HDF5 file being included when CUSEHDF5 = no?
2. Why don't we get the error when CUSEHDF5 = yes? Is this file not getting included (seems like it would have to)? In that case, is HDF5 even working?

**Comment by fumik** [comment]
This issue was fixed and committed .

**Comment by apw6** [comment]
Was the commit pushed?
